
**Step 1 of 3 — Data Acquisition & Cleaning**

Downloads the ULB Credit Card Fraud Detection dataset from Kaggle, validates the expected schema, cleans the data, and outputs cleaned.csv.

How to run: ingest.ipynb → enrich.ipynb → load_mongo.ipynb

In [6]:
import os
import logging
import pandas as pd

In [3]:
#Configuration
#Expected columns in the raw ULB dataset
REQUIRED_COLUMNS = (
    ["Time"] +
    [f"V{i}" for i in range(1, 29)] +
    ["Amount", "Class"]
)
RAW_PATH = "creditcard.csv"
OUTPUT_PATH = "cleaned.csv"

In [4]:
#Download Dataset
# Load dataset from Colab /content folder
if not os.path.exists(RAW_PATH):
    raise FileNotFoundError(f"Upload creditcard.csv to the Colab Files panel first.")

In [8]:
# Load raw data
df_raw = pd.read_csv(RAW_PATH)
df_raw.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [9]:
# Load raw data
df_raw = pd.read_csv(RAW_PATH)
logging.info(f"Loaded {len(df_raw)} rows, {len(df_raw.columns)} columns.")
df_raw.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [10]:
# Clean data — drop duplicates, nulls, invalid Class and Amount values
df_clean = df_raw.drop_duplicates().dropna()
df_clean = df_clean[df_clean["Class"].isin([0, 1])]
df_clean = df_clean[df_clean["Amount"] >= 0]
df_clean["Class"] = df_clean["Class"].astype(int)

logging.info(f"Cleaned data: {len(df_clean)} rows | Fraud rate: {df_clean['Class'].mean():.4%}")
df_clean.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [11]:
#Summary Statitics
print(df_clean["Class"].value_counts())
print(df_clean["Amount"].describe().round(2))

Class
0    283253
1       473
Name: count, dtype: int64
count    283726.00
mean         88.47
std         250.40
min           0.00
25%           5.60
50%          22.00
75%          77.51
max       25691.16
Name: Amount, dtype: float64

In [12]:
#saving the clean data
df_clean.to_csv(OUTPUT_PATH, index=False)
logging.info(f"Cleaned data saved to {OUTPUT_PATH}")